# Generated by Django 4.1.2 on 2022-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.ManyToManyField(to='home.client'),
        ),
    ]
