# Generated by Django 4.1.2 on 2022-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_doctor_patient_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ManyToManyField(to='home.images'),
        ),
    ]
